# Generated by Django 5.0.4 on 2024-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproduccion',
            name='fecha_produccion',
            field=models.DateField(),
        ),
    ]
